version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:17.2.0

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      # - checkout
      - run:
          name: Install dependencies
          command: npm install

  run-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo "Test completed!"

  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/workspace
      - run:
          name: Install AWS CLI
          command: |
            sudo pip install awscli
            aws --version
      - run:
          name: Deploy to S3
          command: |
            aws s3 sync /home/circleci/workspace/build s3://your-bucket-name --delete

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
      - build:
          requires:
            - run-tests
      - deploy:
          requires:
            - build
